defmodule Chronik do
  @moduledoc """
  Documentation for Chronik.

  A lightweight event sourcing/CQRS micro framework for Elixir.
  """

  @typedoc """
  The `event` type represents domain events that are generated by
  the aggregates and consumed by the projection.
  """
  @type event   :: term()

  @typedoc """
  The type of possible streams.

  In `Chronik` the convention used is that the stream for an aggregate is the 
  tuple `{aggregate_module, aggregte_id}`.
  """
  @type stream :: term()
end
